name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: De-bloat stock image
      run: |
        rm -r /run/host/usr/share/dotnet
        rm -r /run/host${{ runner.tool_cache }}

    - name: Install needed packages
      run: apt update && apt install dpkg-dev build-essential debhelper -y

    - name: Build debian package
      run: |
        dpkg-buildpackage --no-sign
        mv ../*.deb ../base-files.deb
    
    - name: Calculate and Save Checksums
      run: |
        sha256sum /__w/base-files/base-files.deb >> checksums.txt
  
    - uses: actions/upload-artifact@v4
      with:
        name: base-files
        path: |
            /__w/base-files/base-files.deb
            checksums.txt

    - uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          /__w/base-files/base-files.deb
          checksums.txt
